server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-realm

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  timelimiter:
    instances:
      productService:
        timeoutDuration: 3s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.order_service.client: DEBUG




#server:
#  port: 8081
#
#spring:
#  application:
#    name: order-service
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecommerce_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  kafka:
#    bootstrap-servers: localhost:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#    consumer:
#      group-id: order-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#
#      properties:
#        spring.json.trusted.packages: "*"
#
#    admin:
#      auto-create: true
#      
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true     
#     
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#  instance:
#    prefer-ip-address: true
#
#resilience4j:
#  timelimiter:
#    instances:
#      productService:
#        timeoutDuration: 3s
#        cancelRunningFuture: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#  endpoint:
#    health:
#      show-details: always
#
#logging:
#  level:
#    com.order_service.client: DEBUG
#    
#    
#    
#  security:
#    oauth2: 
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/ecommerce-realm