## ===============================
## Application Info
## ===============================
#server.port=8082
#spring.application.name=product-service
#
## ===============================
## PostgreSQL Database Configuration
## ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===============================
## JPA / Hibernate Configuration
## ===============================
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## ===============================
## Connection Pool (HikariCP)
## ===============================
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#
## ===============================
## Logging
## ===============================
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
#logging.level.root=INFO
#logging.level.com.product_service=DEBUG
#
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
#
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka