server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  cache:
    type: redis

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.product_service: DEBUG
    org.springframework.cache: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"


#server:
#  port: 8082
#
#spring:
#  application:
#    name: product-service
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecommerce_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  kafka:
#    bootstrap-servers: localhost:9092
#
#    consumer:
#      group-id: product-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 60000  
#  cache: 
#    type: redis
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    com.product_service: DEBUG
#    org.springframework.cache: TRACE
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"